version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    environment:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
              pwd
              current_path=$(pwd)
              apt -y update
              apt -y install wget unzip build-essential checkinstall cmake pkg-config yasm git gfortran libjpeg8-dev libpng-dev software-properties-common
              add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
              apt -y update && apt -y install libjasper1 libtiff-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev
              cd /usr/include/linux
              ln -s -f ../libv4l1-videodev.h videodev.h
              cd $current_path
              apt -y install libgtk2.0-dev libtbb-dev libatlas-base-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev libavresample-dev x264 v4l-utils libwebp-dev tesseract-ocr libtesseract-dev libleptonica-dev

      - run:
          name: Download OpenCV source code
          command: |
              wget https://github.com/opencv/opencv/archive/4.1.1.zip -Oopencv-4.1.1.zip && unzip opencv-4.1.1.zip
              wget https://github.com/opencv/opencv_contrib/archive/4.1.1.zip -Oopencv_contrib-4.1.1.zip && unzip opencv_contrib-4.1.1.zip

      - restore_cache:
          keys:
            - opencv-v4.1.1

      - run:
          name: Build OpenCV
          command: |
              cd opencv-4.1.1 && mkdir build && cd build
              if [ ! -d /root/project/opencv_ubuntu ]; then
                  cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.1/modules -DENABLE_CXX11=ON -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DCMAKE_INSTALL_PREFIX=/root/project/opencv_ubuntu ..
                  make -j4
                  make install
                  ldconfig
                  cd ../../
              fi
              pwd
              ls
              echo "-----"
              ls /root/project/opencv_ubuntu
              echo "-----"
              ls /root/project/opencv_ubuntu/lib

      - save_cache:
          key: opencv-v4.1.1
          paths:
            - /root/project/opencv_ubuntu

      - run:
          name: Build OpenCvSharpExtern
          command: |
              mkdir src/build && cd $_
              cmake -D CMAKE_PREFIX_PATH=/root/project/opencv_ubuntu ..
              make -j4
              ls 
              ls OpenCvSharpExtern
              cp OpenCvSharpExtern/libOpenCvSharpExtern.so /root/project/nuget/

      - run:
          name: Create NuGet package
          command: |
            apt -y install nuget
            mkdir /root/project/artifacts_ubuntu
            nuget pack /root/project/nuget/OpenCvSharp4.runtime.ubuntu.18.04-x64.nuspec -OutputDirectory /root/project/artifacts_ubuntu -Version 4.1.1.`date "+%Y%m%d"`

      - store_artifacts:
          path: /root/project/artifacts_ubuntu

      - run:
          name: Install .NET Core
          command: |
              wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
              dpkg -i packages-microsoft-prod.deb
              add-apt-repository universe
              apt update
              apt -y install apt-transport-https
              apt update
              apt -y install dotnet-sdk-2.2

      - run:
          name: Test
          command: |
            pwd
            ls
            cd /root/project/test/OpenCvSharp.Tests
            ls
            dotnet build -c Release -f netcoreapp2.2
            cp /root/project/nuget/libOpenCvSharpExtern.so /root/project/test/OpenCvSharp.Tests/bin/Release/netcoreapp2.2/
            cp /root/project/nuget/libOpenCvSharpExtern.so /root/project/test/OpenCvSharp.Tests/
            ls /root/project/test/OpenCvSharp.Tests/bin/Release/netcoreapp2.2/
            ldd ./libOpenCvSharpExtern.so
            LD_DEBUG=libs LD_LIBRARY_PATH=. dotnet test OpenCvSharp.Tests.csproj -c Release -f netcoreapp2.2 --runtime ubuntu.18.04-x64
            ls
